name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag: [3.13.5]

    container: alpine:${{ matrix.tag }}

    steps:
      - run: |
          apk update && apk add file git bash make python3 libtool autoconf automake libtool libc-dev

      - uses: actions/checkout@v3
      - run: make submodules

      - run: ./autogen.sh --help

      - run: make autoconf
      - run: mkdir -p  /usr/local/share/man/man1/
      - run: make nostril-clean && make nostril
