name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag: [3.13.5]#, 3.10.9, 3.11.11, 3.12.7, 3.13.5]

    container: alpine:${{ matrix.tag }}

    steps:
      - run: |
          apk update && apk add file git bash make python3 gcompat libtool
          #exec bash && make brew
          #./install-brew.sh

      - uses: actions/checkout@v3

      - run: ./autogen.sh --help
      - run: ./autogen.sh -h
      - run: ./autogen.sh -V
      - run: ./autogen.sh --version
      - run: ./autogen.sh env
        #- run: if [[ ! -d "ctags" ]]; then git clone https://github.com/universal-ctags/ctags; fi

        #- run: cp autogen.sh ctags
        #- run: cp autogen.rc ctags

        #- run: exec bash && cd ctags && ./autogen.sh configure
        #- run: cd ctags && ./configure --prefix=/usr
        #- run: cd ctags && make
        #- run: cd ctags && make install
        #- run: file /usr/bin/ctags
        #- run: /usr/bin/ctags --version
      - run: make autoconf
